### ISSUE TITLE
[Suggestion] Move the Contribution guide (Rules) to another file

### ISSUE THREAD

**Issue by msynk** [efonsecab/Companies-Using-Blazor#1]
Great job opening this repo. 👍
I prefer to see only the actual list of the companies when opening the repo and seeing the README.md content. So I suggest adding a new file named CONTRIBUTION.md and explaining the rules there to have a cleaner README.md for this repo.

**Comment by efonsecab** [comment]
Thanks @msynk , you are right, that would be better and would make it more difficult to quickly reach the limits of the readme file.

**Comment by efonsecab** [comment]
@all-contributors please add @msynk for doc.

**Comment by efonsecab** [comment]
Rules have been moved out from the main README. Closing the ticket.
Please let me know if there is anything else you may think it would be good to add.
